apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  selector:
    matchLabels:
      app: apigateway
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: cloud-gateway
        image: saadrahmanwarsi/cloudgatewayoc:1.1.1
        ports:
        - containerPort: 9391