apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeofbus-deployment
spec:
  selector:
    matchLabels:
      app: timeofbus
  replicas: 1
  template:
    metadata:
      labels:
        app: timeofbus
    spec:
      containers:
      - name: time-of-bus-oc
        image: saadrahmanwarsi/timeofbusoc:1.1.1
        ports:
        - containerPort: 9051