apiVersion: apps/v1
kind: Deployment
metadata:
  name: communicateoc-deployment
spec:
  selector:
    matchLabels:
      app: communicateoc
  replicas: 1
  template:
    metadata:
      labels:
        app: communicateoc
    spec:
      containers:
      - name: communicate-with-oc
        image: saadrahmanwarsi/communicatewithoc:1.1.1
        ports:
        - containerPort: 9057