apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: service-registry
        image: saadrahmanwarsi/serviceregistryoc:1.1.1
        ports:
        - containerPort: 8761