version: '3'
services:
  config-server:
    image: configserveroc
    expose:
      - 9296
    ports: 
      - 9296:9296
    networks:
      - octranspo
  service-registry:
    image: serviceregistryoc
    expose:
      - 8761
    ports: 
      - 8761:8761
    networks:
      - octranspo
  cloud-gateway:
    image: cloudgatewayoc
    expose:
      - 9391
    ports:
      - 9391:9391
    networks:
      - octranspo
    depends_on:
      - config-server
      - service-registry
  communicate-with-oc:
    image: communicatewithoc:1.0.0
    expose:
      - 9057
    ports: 
      - 9057:9057
    networks:
      - octranspo
    depends_on:
      - config-server
      - service-registry
  time-of-bus-oc:
    image: timeofbusoc:1.0
    expose:
      - 9051
    ports: 
      - 9051:9051
    networks:
      - octranspo
    depends_on:
      - config-server
      - service-registry
networks:
  octranspo:
    driver: bridge 
      
    